
setwd("C:/lab/esame/")
library(raster)
library(raster)
library(ncdf4)
library(rgdal)
library(RStoolbox)
library(ggplot2)
coastlines <- readOGR("ne_10m_coastline.shp")
rlist=list.files(pattern="temp", full.names=T)
list_temp =lapply(rlist, raster)
land_t <- stack(list_temp)
cl <- colorRampPalette(c('cyan', 'purple', 'red')) (300)
plot(land_t,col=cl,main="T° dal 2012 al 2020", adj=0.5, zlim=c(0,5))
plot(coastlines)
difT <- temp_2020-temp_2012
cldiff <- colorRampPalette(c('blue','orange','red'))(100)
plot(difT, col=cldiff, main= "grafico differenza tra l'anno 2020 e 2012")
plot(coastlines, add=T)
